### ISSUE TITLE
Frontend - Sprint 1 entrega 18/09

### ISSUE THREAD

**Issue by Conichan** [OrganizacionProyecto/Proyecto#7]
-Producción del sitio web de la tienda navegable con estructura HTML, semántica, estilos CSS y Bootstrap con un mínimo de 3 páginas web inicialmente. (No es plantilla mockup, ni imagen). Páginas web candidatas: landing page, quienes somos, contacto, galería de productos con posibilidad de acceder a la descripción de cada producto o servicio.
 
-Responsive. Requerimiento fundamental.

**Comment by waltercamino** [comment]
el objetivo fue alcanzado con exito en esta primera entrega. Se siguen haciendo correcciones considerando el feedback del cliente
