### ISSUE TITLE
Backend - Sprint 1 entrega 18/09

### ISSUE THREAD

**Issue by Conichan** [OrganizacionProyecto/Proyecto#8]
-En relación a la Abstracción, se debe crear el Diagrama de Clases (modelo de objetos). Pueden usar como herramienta también https://app.diagrams.net/.

-En relación a la Modularización, se debe construir las clases utilizando el lenguaje de programación en Python. 

-En relación a la persistencia de los datos, se debe diseñar la base de datos (diseño conceptual, lógico y físico).

**Comment by sinistri** [comment]
Se relizaron Historias de usuario de backend, a medida que se agreguen funcionalidades se agregaran las historias de usuarios correspondientes

**Comment by sinistri** [comment]
Se relizaron Historias de usuario de backend, a medida que se agreguen funcionalidades se agregaran las historias de usuarios correspondientes
